// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwYgJY0NVSqmlSnIQrIAlANqbVHkybDyg',
    appId: '1:202770267904:web:a9e3bc2f4e0bad22947de5',
    messagingSenderId: '202770267904',
    projectId: 'asynconf-7f274',
    authDomain: 'asynconf-7f274.firebaseapp.com',
    storageBucket: 'asynconf-7f274.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nlEV5cBK5rnWsrOzaxUgp5ihk1q8_tU',
    appId: '1:202770267904:android:9db7d6e697f51a0d947de5',
    messagingSenderId: '202770267904',
    projectId: 'asynconf-7f274',
    storageBucket: 'asynconf-7f274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJUz4iPfl2DDWiMmKYvM59DNO-NGAJNM',
    appId: '1:202770267904:ios:fb4c6e9aa2e063ce947de5',
    messagingSenderId: '202770267904',
    projectId: 'asynconf-7f274',
    storageBucket: 'asynconf-7f274.appspot.com',
    iosClientId: '202770267904-8jdkikv1vgpo3g4bstalfeeg5tj3q30r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testUn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJUz4iPfl2DDWiMmKYvM59DNO-NGAJNM',
    appId: '1:202770267904:ios:fb4c6e9aa2e063ce947de5',
    messagingSenderId: '202770267904',
    projectId: 'asynconf-7f274',
    storageBucket: 'asynconf-7f274.appspot.com',
    iosClientId: '202770267904-8jdkikv1vgpo3g4bstalfeeg5tj3q30r.apps.googleusercontent.com',
    iosBundleId: 'com.example.testUn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwYgJY0NVSqmlSnIQrIAlANqbVHkybDyg',
    appId: '1:202770267904:web:d16202394fe3422b947de5',
    messagingSenderId: '202770267904',
    projectId: 'asynconf-7f274',
    authDomain: 'asynconf-7f274.firebaseapp.com',
    storageBucket: 'asynconf-7f274.appspot.com',
  );
}
